# Generated by Django 5.1.7 on 2025-03-30 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_petminder_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petminder',
            name='credentials',
        ),
    ]
